apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-svc
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-svc
  template:
    metadata:
      labels:
        app: demo-svc
    spec:
      containers:
        - name: demo-svc
          image: "{{ .Values.image }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
